heat_pwm_ECO=1023
heat_pwm_NORMAL=500
heat_pwm_STRONG=250
heat_pwm_FAST=0

heat_p_NIGHT_LIT="NORMAL"
heat_p_NIGHT_DRK="ECO"
heat_p_MORNING_LIT="STRONG"
heat_p_MORNING_DRK="STRONG"
heat_p_ATHOME_LIT="NORMAL"
heat_p_ATHOME_DRK="NORMAL"
heat_p_AWAY_LIT="NORMAL"
heat_p_AWAY_DRK="ECO"
heat_p_EVENING_LIT="NORMAL"
heat_p_EVENING_DRK="NORMAL"
heat_p_TOBED_LIT="NORMAL"
heat_p_TOBED_DRK="ECO"
